# Generated by Django 5.2 on 2025-10-02 15:03

import onboarding_ops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProviderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PROVIDER_RECORDS_REVIEW", "Provider Records Review"),
                            ("MISCELLANEOUS", "miscellaneous"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProviderForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        help_text="e.g., 'New Account Form', 'IVR Report'",
                        max_length=100,
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "completed_form",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=onboarding_ops.models.provider_form_upload_path,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "form_data",
                    models.JSONField(
                        blank=True,
                        help_text="A snapshot of the form's data.",
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
