# Generated by Django 5.2.7 on 2025-10-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProviderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROVIDER_RECORDS_REVIEW", "Provider Records Review"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        default="MISCELLANEOUS",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about the document upload (e.g., email recipient, file count)",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Provider Document",
                "verbose_name_plural": "Provider Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        help_text="e.g., 'New Account Form', 'IVR Report'",
                        max_length=100,
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "completed_form",
                    models.CharField(
                        blank=True,
                        help_text="Azure blob path to the completed form",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "form_data",
                    models.JSONField(
                        blank=True,
                        help_text="A snapshot of the form's data.",
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
