# Generated by Django 5.2.7 on 2025-10-24 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("onboarding_ops", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    # **FIX: Replaced duplicated 'user' AddField with no-op.**
    migrations.RunSQL('SELECT 1'), 
    
    # This AddField for 'patient' must remain, unless it also causes an error later.
    migrations.AddField(
        model_name="providerform",
        name="patient",
        field=models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            to="patients.patient",
        ),
    ),
    
    # **FIX: Replaced duplicated 'user' AddField with no-op.**
    migrations.RunSQL('SELECT 1'), 

    migrations.AddIndex(
        model_name="providerform",
        index=models.Index(
            fields=["user", "form_type", "completed"],
            name="onboarding__user_id_f0a689_idx",
        ),
    ),
    migrations.AddIndex(
        model_name="providerform",
        index=models.Index(
            fields=["submission_id"], name="onboarding__submiss_ccaa53_idx"
        ),
    ),
]
