# Generated by Django 5.2 on 2025-10-18 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_ops", "0002_initial"),
        ("patients", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="providerdocument",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="providerform",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterField(
            model_name="providerdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("PROVIDER_RECORDS_REVIEW", "Provider Records Review"),
                    ("MISCELLANEOUS", "Miscellaneous"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="providerform",
            name="completed_form",
            field=models.CharField(
                blank=True,
                help_text="Azure blob path to the completed form",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="providerform",
            index=models.Index(
                fields=["user", "form_type", "completed"],
                name="onboarding__user_id_f0a689_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providerform",
            index=models.Index(
                fields=["submission_id"], name="onboarding__submiss_ccaa53_idx"
            ),
        ),
    ]
