# Generated by Django 5.2 on 2025-10-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
