# Generated by Django 5.2.7 on 2025-10-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notes", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
    # Replaced the failing AddField operation with a no-op to synchronize history.
    # The 'patient_id' column already exists in the database.
    migrations.RunSQL('SELECT 1'), 
]
