# Generated by Django 5.2.7 on 2025-11-04 20:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IVRForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("physician_name", models.CharField(blank=True, max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("facility_address", models.TextField(blank=True)),
                (
                    "facility_city_state_zip",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "wound_size_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wound length in cm (head to toe)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "wound_size_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wound width in cm (side to side, perpendicular to length)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "wound_size_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wound depth in cm (measured at deepest point)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="Azure Blob Storage URL for the generated PDF",
                        max_length=500,
                    ),
                ),
                (
                    "pdf_blob_name",
                    models.CharField(
                        blank=True,
                        help_text="Blob name in Azure Storage",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                            ("withdrawn", "Withdrawn by Provider"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about approval/denial decision",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "IVR Form",
                "verbose_name_plural": "IVR Forms",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "middle_initial",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=20, null=True, region=None
                    ),
                ),
                (
                    "primary_insurance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_insurance_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "secondary_insurance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "secondary_insurance_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tertiary_insurance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tertiary_insurance_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "medical_record_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "wound_size_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wound length in cm (head to toe)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "wound_size_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wound width in cm (side to side, perpendicular to length)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "wound_size_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wound depth in cm (measured at deepest point)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "activate_Account",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Activated", "Activated"),
                            ("Deactivated", "Deactivated"),
                        ],
                        default="Activated",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
