# Generated by Django 5.2 on 2025-10-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ivrform",
            name="provider",
            field=models.ForeignKey(
                help_text="The provider who submitted this IVR form",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ivr_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ivrform",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_ivr_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ivrform",
            name="patient",
            field=models.ForeignKey(
                help_text="The patient this IVR form is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ivr_forms",
                to="patients.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="ivrform",
            index=models.Index(
                fields=["patient", "-submitted_at"],
                name="patients_iv_patient_fc4715_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ivrform",
            index=models.Index(
                fields=["provider", "-submitted_at"],
                name="patients_iv_provide_ac9f4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ivrform",
            index=models.Index(
                fields=["status", "-submitted_at"], name="patients_iv_status_6d0a7c_idx"
            ),
        ),
    ]
