# Generated by Django 5.2 on 2025-12-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="conservative_care",
            field=models.BooleanField(
                default=False,
                help_text="Whether patient requires conservative care approach",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="default_icd10_code",
            field=models.CharField(
                blank=True,
                help_text="Patient's primary ICD-10 code (used for pre-filling)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_chronic_wound",
            field=models.BooleanField(
                default=False, help_text="Whether patient has chronic wounds"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="wound_drainage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("light", "Light"),
                    ("moderate", "Moderate"),
                    ("heavy", "Heavy"),
                ],
                help_text="Typical drainage level for this patient",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="wound_location",
            field=models.CharField(
                blank=True,
                help_text="Patient's primary wound location",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="wound_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slow_healing", "Slow-healing incision"),
                    ("dehisced", "Dehisced wound"),
                    ("dfu", "DFU"),
                    ("vlu", "VLU"),
                ],
                help_text="Patient's primary wound type (used as default for new orders)",
                max_length=20,
                null=True,
            ),
        ),
    ]
