# Generated by Django 5.2 on 2025-12-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="conservative_care",
            field=models.BooleanField(
                default=False, help_text="Conservative care Yes/No"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="icd10_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_chronic_wound",
            field=models.BooleanField(
                default=False, help_text="Other chronic wound checkbox"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="kit_duration",
            field=models.CharField(
                choices=[("30-day", "30-day"), ("15-day", "15-day")],
                default="30-day",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="kit_size",
            field=models.CharField(
                choices=[
                    ("2x2", "2×2 pad"),
                    ("1x1", "1×1 pad"),
                    ("7x7", "7×7 pad"),
                    ("10x10", "10×10 pad"),
                    ("powder", "Powder option"),
                ],
                default="2x2",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recommended_kit",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated recommendation like '30-Day DFU Kit - 2×2 Pad'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="wound_drainage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("light", "Light"),
                    ("moderate", "Moderate"),
                    ("heavy", "Heavy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wound_location",
            field=models.CharField(
                blank=True,
                help_text="Location of wound on body",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wound_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slow_healing", "Slow-healing incision"),
                    ("dehisced", "Dehisced wound"),
                    ("dfu", "DFU"),
                    ("vlu", "VLU"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
